const projects = [
  { id: "001", number: 1, title: "Landing Page", description: "This ended up spiraling into 5 days of building and taught me a lot about the role of planning and designing AHEAD of building.", category: "Webpage", week: 1, path: "/developer-playground/projects/001-landing-page", status: "in-progress", commits: 12 },
  { id: "002", number: 2, title: "Project Scaffolding", category: "IDK", week: 1, path: "/developer-playground/projects/002-project-scaffolding", status: "live", tags: [], commits: 0 },
  { id: "003", number: 3, title: "About Page", category: "Webpage", week: 2, path: "/developer-playground/projects/003-about-page", status: "live", tags: [], commits: 0 },
  { id: "004", number: 4, title: "Dark Mode", category: "CSS Theme", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "005", number: 5, title: "Print Stylesheet", category: "CSS Theme", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "006", number: 6, title: "404 error page", category: "Webpage", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "007", number: 7, title: "Rock. Paper. Scissors. Lizard. Spock.", category: "Game", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "008", number: 8, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "009", number: 9, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "010", number: 10, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "011", number: 11, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "012", number: 12, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "013", number: 13, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "014", number: 14, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "015", number: 15, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "016", number: 16, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "017", number: 17, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "018", number: 18, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "019", number: 19, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "020", number: 20, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "021", number: 21, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "022", number: 22, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "023", number: 23, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "024", number: 24, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "025", number: 25, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "026", number: 26, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "027", number: 27, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "028", number: 28, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "029", number: 29, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "030", number: 30, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "031", number: 31, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "032", number: 32, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "033", number: 33, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "034", number: 34, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "035", number: 35, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "036", number: 36, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "037", number: 37, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "038", number: 38, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "039", number: 39, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "040", number: 40, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "041", number: 41, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "042", number: 42, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "043", number: 43, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "044", number: 44, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "045", number: 45, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "046", number: 46, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "047", number: 47, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "048", number: 48, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "049", number: 49, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "050", number: 50, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "051", number: 51, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "052", number: 52, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "053", number: 53, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "054", number: 54, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "055", number: 55, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "056", number: 56, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "057", number: 57, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "058", number: 58, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "059", number: 59, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "060", number: 60, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "061", number: 61, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "062", number: 62, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "063", number: 63, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "064", number: 64, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "065", number: 65, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "066", number: 66, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "067", number: 67, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "068", number: 68, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "069", number: 69, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "070", number: 70, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "071", number: 71, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "072", number: 72, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "073", number: 73, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "074", number: 74, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "075", number: 75, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "076", number: 76, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "077", number: 77, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "078", number: 78, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "079", number: 79, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "080", number: 80, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "081", number: 81, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "082", number: 82, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "083", number: 83, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "084", number: 84, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "085", number: 85, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "086", number: 86, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "087", number: 87, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "088", number: 88, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "089", number: 89, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "090", number: 90, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "091", number: 91, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "092", number: 92, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "093", number: 93, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "094", number: 94, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "095", number: 95, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "096", number: 96, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "097", number: 97, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "098", number: 98, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "099", number: 99, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "100", number: 100, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "101", number: 101, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "102", number: 102, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "103", number: 103, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "104", number: 104, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "105", number: 105, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "106", number: 106, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "107", number: 107, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "108", number: 108, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "109", number: 109, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "110", number: 110, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "111", number: 111, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "112", number: 112, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "113", number: 113, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "114", number: 114, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "115", number: 115, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "116", number: 116, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "117", number: 117, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "118", number: 118, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "119", number: 119, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "120", number: 120, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "121", number: 121, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "122", number: 122, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "123", number: 123, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "124", number: 124, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "125", number: 125, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "126", number: 126, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "127", number: 127, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "128", number: 128, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "129", number: 129, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "130", number: 130, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "131", number: 131, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "132", number: 132, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "133", number: 133, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "134", number: 134, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "135", number: 135, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "136", number: 136, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "137", number: 137, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "138", number: 138, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "139", number: 139, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "140", number: 140, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "141", number: 141, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "142", number: 142, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "143", number: 143, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "144", number: 144, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "145", number: 145, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "146", number: 146, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "147", number: 147, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "148", number: 148, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "149", number: 149, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "150", number: 150, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "151", number: 151, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "152", number: 152, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "153", number: 153, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "154", number: 154, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "155", number: 155, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "156", number: 156, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "157", number: 157, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "158", number: 158, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "159", number: 159, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "160", number: 160, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "161", number: 161, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "162", number: 162, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "163", number: 163, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "164", number: 164, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "165", number: 165, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "166", number: 166, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "167", number: 167, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "168", number: 168, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "169", number: 169, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "170", number: 170, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "171", number: 171, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "172", number: 172, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "173", number: 173, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "174", number: 174, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "175", number: 175, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "176", number: 176, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "177", number: 177, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "178", number: 178, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "179", number: 179, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "180", number: 180, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "181", number: 181, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "182", number: 182, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "183", number: 183, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "184", number: 184, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "185", number: 185, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "186", number: 186, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "187", number: 187, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "188", number: 188, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "189", number: 189, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "190", number: 190, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "191", number: 191, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "192", number: 192, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "193", number: 193, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "194", number: 194, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "195", number: 195, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "196", number: 196, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "197", number: 197, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "198", number: 198, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "199", number: 199, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "200", number: 200, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "201", number: 201, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "202", number: 202, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "203", number: 203, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "204", number: 204, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "205", number: 205, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "206", number: 206, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "207", number: 207, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "208", number: 208, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "209", number: 209, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "210", number: 210, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "211", number: 211, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "212", number: 212, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "213", number: 213, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "214", number: 214, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "215", number: 215, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "216", number: 216, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "217", number: 217, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "218", number: 218, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "219", number: 219, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "220", number: 220, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "221", number: 221, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "222", number: 222, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "223", number: 223, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "224", number: 224, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "225", number: 225, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "226", number: 226, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "227", number: 227, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "228", number: 228, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "229", number: 229, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "230", number: 230, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "231", number: 231, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "232", number: 232, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "233", number: 233, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "234", number: 234, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "235", number: 235, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "236", number: 236, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "237", number: 237, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "238", number: 238, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "239", number: 239, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "240", number: 240, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "241", number: 241, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "242", number: 242, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "243", number: 243, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "244", number: 244, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "245", number: 245, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "246", number: 246, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "247", number: 247, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "248", number: 248, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "249", number: 249, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "250", number: 250, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "251", number: 251, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "252", number: 252, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "253", number: 253, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "254", number: 254, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "255", number: 255, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "256", number: 256, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "257", number: 257, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "258", number: 258, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "259", number: 259, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "260", number: 260, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "261", number: 261, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "262", number: 262, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "263", number: 263, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "264", number: 264, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "265", number: 265, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "266", number: 266, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "267", number: 267, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "268", number: 268, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "269", number: 269, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "270", number: 270, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "271", number: 271, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "272", number: 272, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "273", number: 273, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "274", number: 274, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "275", number: 275, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "276", number: 276, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "277", number: 277, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "278", number: 278, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "279", number: 279, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "280", number: 280, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "281", number: 281, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "282", number: 282, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "283", number: 283, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "284", number: 284, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "285", number: 285, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "286", number: 286, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "287", number: 287, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "288", number: 288, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "289", number: 289, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "290", number: 290, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "291", number: 291, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "292", number: 292, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "293", number: 293, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "294", number: 294, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "295", number: 295, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "296", number: 296, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "297", number: 297, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "298", number: 298, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "299", number: 299, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "300", number: 300, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "301", number: 301, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "302", number: 302, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "303", number: 303, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "304", number: 304, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "305", number: 305, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "306", number: 306, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "307", number: 307, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "308", number: 308, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "309", number: 309, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "310", number: 310, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "311", number: 311, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "312", number: 312, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "313", number: 313, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "314", number: 314, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "315", number: 315, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "316", number: 316, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "317", number: 317, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "318", number: 318, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "319", number: 319, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "320", number: 320, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "321", number: 321, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "322", number: 322, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "323", number: 323, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "324", number: 324, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "325", number: 325, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "326", number: 326, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "327", number: 327, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "328", number: 328, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "329", number: 329, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "330", number: 330, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "331", number: 331, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "332", number: 332, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "333", number: 333, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "334", number: 334, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "335", number: 335, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "336", number: 336, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "337", number: 337, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "338", number: 338, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "339", number: 339, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "340", number: 340, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "341", number: 341, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "342", number: 342, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "343", number: 343, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "344", number: 344, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "345", number: 345, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "346", number: 346, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "347", number: 347, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "348", number: 348, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "349", number: 349, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "350", number: 350, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "351", number: 351, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "352", number: 352, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "353", number: 353, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "354", number: 354, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "355", number: 355, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "356", number: 356, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "357", number: 357, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "358", number: 358, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "359", number: 359, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "360", number: 360, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "361", number: 361, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "362", number: 362, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "363", number: 363, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "364", number: 364, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
  { id: "365", number: 365, title: "", category: "", week: false, path: "", status: "planned", tags: [], commits: 0 },
];

const allProjects = projects
  .filter((p) => p.status === 'live' || p.status === 'in-progress')
  .sort((a, b) => b.number - a.number);

const recentProjects = allProjects.slice(0, 5);

const mainProjectElement = allProjects
  .map((p) => `
    <article class="card card-project">
      <p class="label">${p.status === 'live' ? 'Live' : 'In Progress'}</p>
      <h3><a href="${p.path}">${p.title}</a></h3>
      <p>${p.description}</p>
    </article>
  `)
  .join('');

const recentProjectElement = recentProjects
  .map((p) => `
    <article class="card card-project">
      <p class="label">${p.status === 'live' ? 'Live' : 'In Progress'}</p>
      <h3><a href="${p.path}">${p.title}</a></h3>
      <p>${p.description}</p>
    </article>
  `)
  .join('');

const curriculumElement = `
  <h2>Curriculum</h2>
  <ul class="curriculum-list">
    ${projects
      .map(
        (p) => `
          <li>
            <h3></h3>
            <p>Project ${p.id} | ${p.category}</p>
            <p class="bold"><a href="${p.path}">${p.title}</a></p>
          </li>
        `
      )
      .join('')}
  </ul>
`;